# FileHatch Go Linter Configuration
# 이 설정은 코드 품질을 유지하기 위한 린트 규칙입니다.

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet         # Go vet 검사
    - staticcheck   # 정적 분석 (gosimple 포함)
    - unused        # 사용되지 않는 코드 검사
  disable:
    - errcheck      # 에러 반환값 체크 (대규모 리팩토링 필요하여 비활성화)

issues:
  # 최대 이슈 수 (0 = 무제한)
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # 테스트 파일에서는 일부 규칙 완화
    - path: _test\.go
      linters:
        - errcheck
    # staticcheck QF (quickfix) 제안 무시
    - text: "QF1003"
      linters:
        - staticcheck
